#
# gp-node-devenv
# Copyright (c) 2023, Greg PFISTER. MIT License.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Build and validate

name: dispatch

on:
  workflow_dispatch:
    inputs:
      ubuntuVersion:
        description: Ubuntu version
        required: true
        type: string

jobs:
  deploy:
    name: Push ghcr.io/gp-devenv/gp-node-devenv
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        nodeVersion: ['14', '16', '18']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup buildx
        run: (cd src && ./scripts/buildx/setup.sh)
      - name: Authenticating
        run: echo $GHCR_IO_TOKEN | docker login ghcr.io -u gpfister --password-stdin
        env:
          GHCR_IO_TOKEN: ${{ secrets.ghcr_io_token }}
      # - name: Build using ghcr.io/gp-devenv/gp-base-devenv:${{ github.event.inputs.ubuntuVersion }} using Node.js v${{ matrix.nodeVersion }}
      #   run: (cd src && ./scripts/buildx/build.sh $UBUNTU_VERSION $NODE_VERSION)
      #   env:
      #     UBUNTU_VERSION: ${{ github.event.inputs.ubuntuVersion }}
      #     NODE_VERSION: ${{ matrix.nodeVersion }}
      - name: Build  and push to ghcr.io/gp-devenv/gp-node-devenv:${{ github.event.inputs.ubuntuVersion }}-${{ matrix.nodeVersion }}
        run: (cd src && ./scripts/buildx/push.sh $UBUNTU_VERSION $NODE_VERSION)
        env:
          UBUNTU_VERSION: ${{ github.event.inputs.ubuntuVersion }}
          NODE_VERSION: ${{ matrix.nodeVersion }}
      - name: Dispatch to ghcr.io/gp-devenv/gp-firebase-devenv repository
        run: |
          curl -X POST \
               -H "Authorization: Bearer $GHCR_IO_TOKEN" \
               -H "X-Github-Api-Version: 2022-11-28" \
               -H "Content-Type: application/json" \
               https://api.github.com/repos/gp-devenv/gp-firebase-devenv/actions/workflows/dispatch.yaml/dispatches \
               --data '{"ref":"master","inputs":{"ubuntuVersion":"${{ matrix.nodeVersion }}","nodeVersion":"${{ matrix.nodeVersion }}"}}'
        env:
          GHCR_IO_TOKEN: ${{secrets.ghcr_io_token}}
      - name: Dispatch to ghcr.io/gp-devenv/gp-angular-devenv repository
        run: |
          curl -X POST \
               -H "Authorization: Bearer $GHCR_IO_TOKEN" \
               -H "X-Github-Api-Version: 2022-11-28" \
               -H "Content-Type: application/json" \
               https://api.github.com/repos/gp-devenv/gp-angular-devenv/actions/workflows/dispatch.yaml/dispatches \
               --data '{"ref":"master","inputs":{"ubuntuVersion":"${{ github.event.inputs.ubuntuVersion }}","nodeVersion":"${{ matrix.nodeVersion }}"}}'
        env:
          GHCR_IO_TOKEN: ${{secrets.ghcr_io_token}}
# End
